#!/usr/bin/env node

const commander = require("commander");
const shell = require("shelljs");
const path = require("path");

commander
  .command("build")
  .description("Tests the update version feature")
  .option('--project <project_name>')
  .action(async (options) => {
    const ng = path.join(__dirname, "node_modules", ".bin", "ng");
    const projectName =  options.project || ".intermediate";
    console.log('using project: ' + projectName);
    const cwd = path.join(__dirname, projectName);
    shell.exec(`${ng} build`, { cwd });
  });

commander
  .command("dev")
  .description("Tests the update version feature")
  .action(async () => {
    const ng = path.join(__dirname, "node_modules", ".bin", "ng");
    const cwd = path.join(__dirname, "_app_test");
    shell.exec(`${ng} serve --project nguxt --configuration=dev`, { cwd });
  });

commander.parse(process.argv);
