#!/usr/bin/env node

const commander = require("commander");
const shell = require("shelljs");
const path = require("path");

commander
  .command("build")
  .description("Tests the update version feature")
  .action(async () => {
    const ng = path.join(__dirname, "node_modules", ".bin", "ng");
    const cwd = path.join(__dirname, "_build");
    shell.exec(`${ng} build --project nguxt`, { cwd });
  });

commander
  .command("dev")
  .description("Tests the update version feature")
  .action(async () => {
    const ng = path.join(__dirname, "node_modules", ".bin", "ng");
    const cwd = path.join(__dirname, "_build");
    shell.exec(`${ng} serve --project nguxt --configuration=dev`, { cwd });
  });

commander.parse(process.argv);
